<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.virginmoney.OneYrFixedRateCashEISATest" tests="6" time="74.137" ignored="0" failures="1" timestamp="20 Oct 2018 20:28:39 GMT" skipped="0" hostname="Latitude" errors="0">
  <testcase name="canValidatePdf" time="11.051" classname="com.virginmoney.OneYrFixedRateCashEISATest"/>
  <testcase name="canValidateRateCard" time="10.294" classname="com.virginmoney.OneYrFixedRateCashEISATest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.virginmoney.OneYrFixedRateCashEISATest.canValidateRateCard(OneYrFixedRateCashEISATest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- canValidateRateCard -->
  <testcase name="canGoTo1YrFRCEISAPage" time="8.953" classname="com.virginmoney.OneYrFixedRateCashEISATest"/>
  <testcase name="canValidateContent" time="27.139" classname="com.virginmoney.OneYrFixedRateCashEISATest"/>
  <testcase name="canValidateShortIntro" time="7.535" classname="com.virginmoney.OneYrFixedRateCashEISATest"/>
  <testcase name="canValidateApplyButton" time="9.165" classname="com.virginmoney.OneYrFixedRateCashEISATest"/>
</testsuite> <!-- com.virginmoney.OneYrFixedRateCashEISATest -->
